baseURL = "https://joelvaneenwyk.github.io/"
languageCode = "en-us"
title = "Joel Van Eenwyk"
theme = "researcher"
publishDir = "."
contentDir = "source/content"
dataDir  = "source/data"
layoutDir = "source/layouts"
themesDir = "source/themes"
assetDir = "source/assets"
archetypeDir = "source/archetypes"